apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebookstore-deployment
  labels:
    app: onlinebookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onlinebookstore
  template:
    metadata:
      labels:
        app: onlinebookstore
    spec:
      containers:
      - name: onlinebookstorecontainer
        image: 
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: obs-svc
spec:
  selector:
    app: onlinebookstore
  ports:
      port: 80
      targetPort: 8080

